language: node_js
node_js:
  - 10
cache:
  yarn: true
  directories:
    - node_modules
env:
  - CI=true
jobs:
  include:
    - name: 'CSS Lint'
      script: yarn test:lint:css
    - name: 'Unit Test Execution'
      script: yarn test
    - stage: deployment
      name: 'Deployment to Heroku'
      before_deploy:
        - yarn build
      deploy:
        provider: heroku
        api_key:
          secure: b84cc163-8808-48d8-b801-a956e01f8636
        app: xt-react-hacker-news
        on:
          repo: AbhishekWadhwa/React-Hacker-News