language: node_js
node_js:
  - 10
cache:
  yarn: true
  directories:
    - node_modules
env:
  - CI=true
jobs:
  include:
    - stage: 'Tests'
      name: 'ES Lint'
      script: yarn test:lint:js
    - name: 'CSS Lint'
      script: yarn test:lint:css
    - name: 'Unit Test Execution'
      script: yarn test
    - stage: deployment
      name: 'Deploy artifacts to Heroku'
      before_deploy:
        - yarn build
      deploy:
        provider: heroku